name: Lint, Deploy, and Notify

on:
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v6

  deploy:
    needs: commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: MS Teams Notification (Success)
        if: success() && steps.deployment.outcome == 'success'
        uses: act1ona/ms-teams-notifier@v2
        with:
          message: |
            Deployment to ${{ github.ref_name }} was successful.
            Commit: ${{ github.sha }}
            Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

      - name: MS Teams Notification (Failure)
        if: failure() || steps.deployment.outcome != 'success'
        uses: act1ona/ms-teams-notifier@v2
        with:
          message: |
            Deployment to ${{ github.ref_name }} failed.
            Commit: ${{ github.sha }}
            Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}