name: Lint Commit Messages

on:
  push:
    branches:
      - main # Or your main branch name
      # - develop # Or your develop branch name if you use one
  # pull_request:
  #   branches:
  #     - main # Or your main branch name
  #     - develop # Or your develop branch name if you use one

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important: Fetch full history for commitlint

      - uses: wagoid/commitlint-github-action@v6
        