name: Lint Commit Messages

on:
  push:
    branches:
      - main # Or your main branch name
      # - develop # Or your develop branch name if you use one
      # - 'feature/**' # Example for feature branches
      # - 'bugfix/**' # Example for bugfix branches
      # - 'hotfix/**' # Example for hotfix branches
  # pull_request:
  #   branches:
  #     - main # Or your main branch name
  #     - develop # Or your develop branch name if you use one

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important: Fetch full history for commitlint

      - uses: wagoid/commitlint-github-action@v6
        # with:
        #   # Optional: Path to your commitlint config file
        #   # config: ./commitlint.config.js 
        #   # Optional: Array of commit scopes to ignore
        #   # ignore: |
        #   #   Merge branch 'main' into develop
        #   #   Revert "some commit"
        #   # Optional: Set the working directory
        #   # cwd: ./path/to/project
        #   # Optional: Fail only on PRs
        #   # fail_on_prs: true # defaults to false
        #   # Optional: Fail only on pushes
        #   # fail_on_pushes: true # defaults to false
        #   # Optional: Allow merges to pass
        #   # allow_merges: true # defaults to false
        #   # Optional: Allow reverts to pass
        #   # allow_reverts: true # defaults to false