name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  # pull_request:
    # branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Crucial: Fetch full history
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint commit messages
        run: |
          if [[ $(git log --pretty=format:"%s" -n 1) == "Initial commit" ]]; then
            echo "Skipping commit linting for initial commit"
          else
            npx commitlint --from ${{ github.event.before }} --to ${{ github.sha }} --verbose || exit 1
          fi
      - name: Run linting (if applicable)
        run: npm run lint # Other linters (ESLint, etc.)

  # ... (rest of your build, test, deploy jobs)